# Site settings
baseurl = "https://jiribatko.com"
languageCode = "en-us"
title = "Jiri Batko"
theme = "hugo-identity-theme"
themesDir = "./themes"

# Disable unnecessary kinds
disableKinds = ["page", "section", "taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT", "404"]

# Enter your tracking code to enable Google Analytics
#googleAnalytics = "UA-116897462-1"

[params]

  # Images settings
  # Icons, backgrounds and avatars folders are placed in theme's static/images folder.
  # You may place your images in corresponding folders and then set only filenames below to
  # change page's appearance

  # Site icons
  favicon_ico = "favicon.ico"
  favicon_ico_sizes = "16x16 32x32"
  appleicon = "apple-icon.png"

  # Additional options to supplement icons served
  #favicon_png = "favicon.png"
  #favicon_png_sizes = "96x96"
  #favicon_svg = "favicon.svg"

  # Link custom assets relative to /static
  #custom_js  = [""]
  custom_css = ["background.css", "icons.css"]

  # Customization switches
  # Overwrite FontAwesome: see icons.css
  #custom_icons = true
  # Overwrite background: see background.css
  custom_background = true

  # Personal data
  [params.personal]
    # If name is not set, author is used
    name = "Jiri Batko"
    # Avatars can be written to images/avatars/
    avatar = "avatar.jpg"
    position = "Full Stack Developer"
    livesIn = "[Vancouver, Canada](https://maps.google.com/maps?ll=49.246292,-123.116226&z=10&t=m&hl=en&gl=US)"
    scope = [
        # "UX for [member dashboard](#)",
        # "Maintainer for [awesome-project](#)",
        # "Open Source [community management](#)"
      ]
    biography = "Java and AWS certified professional with 17+ years of international(New Zealand, UK, Germany, Czech Republic, Canada) experience in software development."

  # Contact form settings
  [params.contact]
    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!

    email = "jiri.batko@gmail.com"

    # It is possible to substitute formspring with other providers
    # as an example the mailout plugin from caddy.
    # Provide the post URL for the form and depending on the provider
    # add some custom JS script to finish the implementation.

    #postURL = "https://example.com/mailout/"

    enable = true
    title = "Contact Me!"
    namePlaceholder = "Name"
    emailPlaceholder = "Your email"
    messagePlaceholder = "Message"
    buttonText = "Send"
    success = "Thank you for contacting me."
    # error = "Message could not be send. Please contact me at "

    # Google invisible captcha
    #[params.contact.captcha]
    #  sitekey = ""


    # Add optional form fields to identify contact forms.
    #[[params.contact.fields.hidden]]
    #  name = "someID"
    #  value = "example.com"

    #[[params.contact.fields.hidden]]
    # Special values for name such as "page" and "site" will be autofilled
    #  name = "page"

  # Social settings
  [[params.social]]
    title = "LinkedIn"
    icon = "fa-linkedin"
    link = "https://www.linkedin.com/in/jiribatko/"
    target = "_blank"

  [[params.social]]
    title = "Facebook"
    icon = "fa-facebook"
    link = "https://www.facebook.com/jiri.batko"
    target = "_blank"

  [[params.social]]
    title = "Instagram"
    icon = "fa-instagram"
    link = "https://www.instagram.com/jiri.batko/"
    target = "_blank"

  [[params.social]]
    title = "Flickr"
    icon = "fa-flickr"
    link = "https://www.flickr.com/photos/31031565@N06/"
    target = "_blank"

  [[params.social]]
    title = "Twitter"
    icon = "fa-twitter"
    link = "https://twitter.com/batkojiri"
    target = "_blank"

  [[params.social]]
    title = "GitHub"
    icon = "fa-github"
    link = "https://github.com/batkoj"
    target = "_blank" 



  # Footer settings
  [params.footer]
    # If copyright is not set, author is used
    copyright = "Jiri Batko"

  # Page license
  [params.license]
    link = "https://creativecommons.org/licenses/by-sa/4.0/legalcode"
    name = "CC-BY-SA-4.0"

  # Credits
  [[params.credits]]
    title = "HUGO"
    text = ""
    link = "https://gohugo.io/"

  [[params.credits]]
    # Title is used as URL text
    title = "HTML5UP"
    # Text will be used to explain the credit
    text = "Design by"
    link = "https://html5up.net"

  # Optional piwik tracking
  #[params.analytics.piwik]
  #  URL = "https://stats.example.com"
  #  ID = "42"
  #  # Track all subdomains with "*.example.com"
  #  domain = "www.example.com"
  #  # Optional integrity check hash
  #  hash = "sha512-RfeD0pacGTqy9m7U6PgehQfS4cc7SIt+e+P+H5e848kEvB/RW84CUGO3O4O3LNbxjevym6KPUZ8muPsMrI8WIw=="
